services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg://app:app@db:5432/app
      ENV: local
      SUPABASE_URL: https://naggrfkksvfxobwbtrji.supabase.co
      SUPABASE_JWT_AUD: authenticated
      SUPABASE_JWT_ISSUER: https://naggrfkksvfxobwbtrji.supabase.co/auth/v1
      SUPABASE_JWT_SECRET: "dc9123db-b271-456f-81bf-df2cd551b5e3"
      SUPABASE_JWTS_URL: https://naggrfkksvfxobwbtrji.supabase.co/auth/v1/.well-known/jwks.json
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  pgdata:
