"""sprint2 blocks model

Revision ID: d48fd4f74c77
Revises: 4a60e2eb8fb2
Create Date: 2026-02-15 19:26:38.511786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd48fd4f74c77'
down_revision: Union[str, None] = '4a60e2eb8fb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_assets',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('VIDEO', name='media_asset_type', native_enum=False), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=127), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_media_assets_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_assets')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_media_assets_storage_key'))
    )
    op.create_index(op.f('ix_media_assets_team_id'), 'media_assets', ['team_id'], unique=False)
    op.create_table('workout_templates',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_workout_templates_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_templates'))
    )
    op.create_index(op.f('ix_workout_templates_team_id'), 'workout_templates', ['team_id'], unique=False)
    op.create_table('exercises',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('video_asset_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_exercises_team_id_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_asset_id'], ['media_assets.id'], name=op.f('fk_exercises_video_asset_id_media_assets'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercises')),
    sa.UniqueConstraint('team_id', 'name', name='uq_exercise_team_name')
    )
    op.create_index(op.f('ix_exercises_team_id'), 'exercises', ['team_id'], unique=False)
    op.create_table('workout_blocks',
    sa.Column('workout_template_id', sa.UUID(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.ForeignKeyConstraint(['workout_template_id'], ['workout_templates.id'], name=op.f('fk_workout_blocks_workout_template_id_workout_templates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_blocks'))
    )
    op.create_index(op.f('ix_workout_blocks_workout_template_id'), 'workout_blocks', ['workout_template_id'], unique=False)
    op.create_table('block_exercises',
    sa.Column('workout_block_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('prescription_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_block_exercises_exercise_id_exercises'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_block_id'], ['workout_blocks.id'], name=op.f('fk_block_exercises_workout_block_id_workout_blocks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_block_exercises')),
    sa.UniqueConstraint('workout_block_id', 'order', name='uq_block_exercise_block_order')
    )
    op.create_index(op.f('ix_block_exercises_exercise_id'), 'block_exercises', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_block_exercises_workout_block_id'), 'block_exercises', ['workout_block_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_block_exercises_workout_block_id'), table_name='block_exercises')
    op.drop_index(op.f('ix_block_exercises_exercise_id'), table_name='block_exercises')
    op.drop_table('block_exercises')
    op.drop_index(op.f('ix_workout_blocks_workout_template_id'), table_name='workout_blocks')
    op.drop_table('workout_blocks')
    op.drop_index(op.f('ix_exercises_team_id'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_workout_templates_team_id'), table_name='workout_templates')
    op.drop_table('workout_templates')
    op.drop_index(op.f('ix_media_assets_team_id'), table_name='media_assets')
    op.drop_table('media_assets')
    # ### end Alembic commands ###
