"""add_memberships_and_invites

Sprint 5 — invite-based onboarding.

Creates two new tables:
  • memberships: links a Supabase user (user_id = JWT 'sub') to a team with
    a role (COACH | ATHLETE).  UNIQUE(user_id, team_id) prevents duplicates.
  • invites: single-use, optionally time-limited codes generated by COACHes.

Both tables are independent of user_profiles so the old onboarding flow
continues to work while the new invite-based flow is introduced.

Revision ID: e1f2a3b4c5d6
Revises: deca97f5042e
Create Date: 2026-02-26
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "e1f2a3b4c5d6"
down_revision: Union[str, None] = "deca97f5042e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ------------------------------------------------------------------ #
    # memberships                                                          #
    # ------------------------------------------------------------------ #
    op.create_table(
        "memberships",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("team_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', NOW())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', NOW())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
            name="fk_memberships_team_id_teams",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_memberships"),
        sa.UniqueConstraint("user_id", "team_id", name="uq_memberships_user_team"),
        sa.CheckConstraint(
            "role IN ('COACH', 'ATHLETE')", name="ck_memberships_user_role"
        ),
    )
    op.create_index("ix_memberships_user_id", "memberships", ["user_id"])
    op.create_index("ix_memberships_team_id", "memberships", ["team_id"])

    # ------------------------------------------------------------------ #
    # invites                                                              #
    # ------------------------------------------------------------------ #
    op.create_table(
        "invites",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("team_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("code", sa.String(64), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_by_user_id", postgresql.UUID(as_uuid=True), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', NOW())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', NOW())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
            name="fk_invites_team_id_teams",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_invites"),
        sa.UniqueConstraint("code", name="uq_invites_code"),
        sa.CheckConstraint(
            "role IN ('COACH', 'ATHLETE')", name="ck_invites_user_role"
        ),
    )
    op.create_index("ix_invites_team_id", "invites", ["team_id"])
    op.create_index("ix_invites_code", "invites", ["code"])
    op.create_index(
        "ix_invites_created_by_user_id", "invites", ["created_by_user_id"]
    )


def downgrade() -> None:
    op.drop_index("ix_invites_created_by_user_id", table_name="invites")
    op.drop_index("ix_invites_code", table_name="invites")
    op.drop_index("ix_invites_team_id", table_name="invites")
    op.drop_table("invites")

    op.drop_index("ix_memberships_team_id", table_name="memberships")
    op.drop_index("ix_memberships_user_id", table_name="memberships")
    op.drop_table("memberships")
