"""add product_events table

Revision ID: ff6f8d76c493
Revises: e1f2a3b4c5d6
Create Date: 2026-02-27 17:17:35.709326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff6f8d76c493'
down_revision: Union[str, None] = 'e1f2a3b4c5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('event_name', sa.Enum('TEAM_CREATED', 'INVITE_ACCEPTED', name='funnel_event'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', NOW())"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_events'))
    )
    op.create_index('ix_product_events_event_name_created_at', 'product_events', ['event_name', 'created_at'], unique=False)
    op.create_index('ix_product_events_team_id_created_at', 'product_events', ['team_id', 'created_at'], unique=False)
    op.create_index('ix_product_events_user_id_created_at', 'product_events', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_events_user_id_created_at', table_name='product_events')
    op.drop_index('ix_product_events_team_id_created_at', table_name='product_events')
    op.drop_index('ix_product_events_event_name_created_at', table_name='product_events')
    op.drop_table('product_events')
    sa.Enum(name="funnel_event").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
